# Generated by Django 5.2.8 on 2025-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
